### ISSUE TITLE
Feature query: Do we have a work queues OpenRPA/OpenFlow

### ISSUE THREAD

**Issue by epamPreth** [open-rpa/openflow#112]
This is a query about a common feature in RPA tools. 
Do we have queues in OpenRPA/OpenFlow to handle work items and processes them one at a time. If not is there is a work around.

**Comment by skadefro** [comment]
I responded in rocket chat, I would like to keep github reserved for bug reports and usage questions on the [forum](https://bb.openiap.io/) or [rocket chat](https://rocket.openiap.io/).
