### ISSUE TITLE
error creating node NodeRed from Openflow

### ISSUE THREAD

**Issue by v17963502** [open-rpa/openflow#116]
Dear,

I have installed an instance of Openflow and Node-Red on Ubuntu 18.04 and when I try to create an instance of Node-Red from OpenFlow I get an error "HTTP request failed". When I check the Log the following is presented:

HttpError: HTTP request failed
    at Request._callback (/usr/local/lib/node_modules/@openiap/openflow/node_modules/@kubernetes/client-node/dist/gen/api/appsV1Api.js:2300:40)
    at Request.self.callback (/usr/local/lib/node_modules/@openiap/openflow/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/@openiap/openflow/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@openiap/openflow/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Please your support.

Regards,

**Comment by skadefro** [comment]
I see your trying to use the kubernetes functionality on what I'm going to assume is NOT an kubernetes installation running on ubuntu. You control and handle nodereds if using npm packages or docker, by using the cli tools or the config yaml file. Only when running on kubernetes is dynamic creation of nodereds supported.
If I miss understood, please let me know.

**Comment by v17963502** [comment]
Dear Allan,

It is correct, My installation is on ubuntu and I am not using Kubernetes. I am just getting to know these tools. Therefore, if you could tell me what parameter I should change in the config file to avoid this error.

Thank you,

**Comment by v17963502** [comment]
Dear Allan,
It is correct, My installation is on ubuntu and I am not using Kubernetes. I am just getting to know these tools. Therefore, if you could tell me what parameter I should change in the config file to avoid this error.
Thank you,


De: Allan Zimmermann ***@***.***>
Enviado el: sábado, 10 de abril de 2021 05:36 a.m.
Para: open-rpa/openflow ***@***.***>
CC: Aguilera, Mirko ***@***.***>; Author ***@***.***>
Asunto: Re: [open-rpa/openflow] error creating node NodeRed from Openflow (#116)


I see your trying to use the kubernetes functionality on what I'm going to assume is NOT an kubernetes installation running on ubuntu. You control and handle nodereds if using npm packages or docker, by using the cli tools or the config yaml file. Only when running on kubernetes is dynamic creation of nodereds supported.
If I miss understood, please let me know.

**Comment by skadefro** [comment]
change "allow_personal_nodered" back to false. This setting is only for kubernetes installations

**Comment by v17963502** [comment]
thank you very much Allan. I ask you, by having this setting, the integration between openflow and Node-Red is maintained. Additionally, do you recommend working with kubernetes? What advantages or disadvantages do I get with this installation kubernetes from the point of view of openflow and Node-Red functionalities?

De: Allan Zimmermann ***@***.***>
Enviado el: martes, 13 de abril de 2021 02:08 a.m.
Para: open-rpa/openflow ***@***.***>
CC: Aguilera, Mirko ***@***.***>; Author ***@***.***>
Asunto: Re: [open-rpa/openflow] error creating node NodeRed from Openflow (#116)


change "allow_personal_nodered" back to false. This setting is only for kubernetes installations

**Comment by skadefro** [comment]
Please don't keep this issue alive with more questions.
Use [rocket chat](https://rocket.openiap.io/) or [the forum](https://bb.openiap.io/) for usage questions
