### ISSUE TITLE
error invoking NodeRed from Openflow

### ISSUE THREAD

**Issue by v17963502** [open-rpa/openflow#129]
I just completed the installation of Openflow and NodeRed in Ubuntu, but when I enter the "Robots" section and invoke NodeRed, the portal opens a blank page where the URL corresponds to the username followed by the URL of the Openflow server

![image](https://user-images.githubusercontent.com/79284483/117360283-95fa6d80-ae86-11eb-84bc-53a4dd8c3643.png)

Thankful in advance with what they can help me.

**Comment by skadefro** [comment]
Is it running in docker or kubernetes ?
If not, then it's YOUR job to handle the nodered instances. ( the url is generated by the nodered_domain_schema varaible, so if you choose another way, you can update that )

**Comment by skadefro** [comment]
Try updating to latest version (1.2.102). I believe it was hardcoded for https until recently

**Comment by skadefro** [comment]
I'm going to assume this works for you now, if not feel free to reach out on the [forum](https://bb.openiap.io/) or [rocket chat](https://rocket.openiap.io)
