### ISSUE TITLE
how to run openflow?

### ISSUE THREAD

**Issue by logcy** [open-rpa/openflow#23]
我要怎么运行openflow的代码呀？

**Comment by skadefro** [comment]
If you want to test it, you can either create an account at https://demo1.openrpa.dk or you can install Docker CE and use one of the two docker-compose examples.
If you want to run and debug the code locally, install mongodb, rabbitmq, nodejs v10 and visual code ... install typescript and gulp using npm -g and the run the code from vs-code, You will need to add an environment file in config/.env you can get inspired by the values  in the 2 docker-compose files or look into config.ts too see all options.

**Comment by skadefro** [comment]
Do you need more help or shall i close this issue ?
