### ISSUE TITLE
how to run openflow?

### ISSUE THREAD

**Issue by logcy** [open-rpa/openflow#25]
Thank you for your reply。But I still have some confusion：
1、After I install typescript and gulp using npm install -g ,how I run this code within vs code or in command line?(Witch command）
2、Whow to build this project ? Using "gulp compose"?But I using "gulp compose" command to build this project ,how to run and how to deploy to tomcat？（I copy "dist/public" under tomcat webapps/ROOT,but i cann't access）

thanks!!

**Comment by skadefro** [comment]
1) node index.js inside the two dist folders or use vscode. Remember to setup environment variables (you can fint those in the two config.ts files, see examples in the docker-compose files )
2) See gulp.js for how to build, but generally you want to at least once, build the webpack. Then using vscode you can start debugging, witch will start the typescript compiler, to copy html files you also need to run the default gulp task
Gulp compose only works for me, you need to modify it to fit your needs
You cannot run openflow from/in tomcat, openflow is a webserver in it self and te project was created to run inside docker (but you can run it outside if need be )
