### ISSUE TITLE
Fix RPA Workflow Naming Bug

### ISSUE THREAD

**Issue by Jelleebeen** [open-rpa/openflow#39]
**Fix RPA Workflow Naming Bug**

I intend to submit a pull request to fix this issue shortly.

Set the default name in rpa.html to allow a name to be set in RPA Workflow nodes.

**Comment by skadefro** [comment]
I've built a new docker image. If you are on docker, just update the docker-compose file to use the [newest version](https://github.com/open-rpa/openflow/blob/master/VERSION) 
If using demo1.openrpa.dk then go to nodered tab, delete your nodered (no data will be lost) then recreate it ... ( you can click create while it's deleting the old one )
