### ISSUE TITLE
How to run openflow alone using node server

### ISSUE THREAD

**Issue by ashokkumarjuly** [open-rpa/openflow#51]
Hi,
I have cloned the repo  and i have followed the steps to run using vscode, its working fine. but i have few questions. but i am confused how to run openrpa only in command line and deploy openflow alone in my test server.

1. Please tell us the steps to run the openflow application in command line without using vscode debug.
2. Whether can we able to run the openflow alone as a service and can we able to change the domain with custom domain name
3. In code where we can modify saml configurations based on the domain.

I am new to openrpa and started to exploring, please help.

**Comment by skadefro** [comment]
Please use slack for help with usage, github is just for bugs.
