### ISSUE TITLE
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/openiap/node_modules/os-service/.node-gyp'

### ISSUE THREAD

**Issue by caodongzhi1976** [open-rpa/openflow#69]
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/openiap/node_modules/os-service/.node-gyp'

use   sudo npm i openiap -g --unsafe-perm

**Comment by skadefro** [comment]
delete the folder manually and try again ... the folder seem to have the wrong permissions

**Comment by skadefro** [comment]
Any luck ? did it help ?

**Comment by skadefro** [comment]
I'll assume you found a solution, if not, please reach out on rocketchat (github is for bugs not usage questions)
