### ISSUE TITLE
OpenFlow NodeRed menu title displays as "Sockets"

### ISSUE THREAD

**Issue by goodfellasthai** [open-rpa/openflow#72]
**Describe the bug**
OpenFlow NodeRed menu title displays as "Sockets"
I think this is incorrect unless it is intended wording

**To Reproduce**
Log into OpenFlow with NodeRed privileges and click the NodeRed menu option

**Expected behavior**
Should say NodeRED

**Screenshots**

**Desktop (please complete the following information):**
 - Using selfhosted openflow but using directly unchanged docker images at 1.0.83

**Comment by skadefro** [comment]
Oh, your right. Funny i notice things like that.
I'll get that updated right away, thank you for reporting this

**Comment by skadefro** [comment]
Fixed in version 1.0.84
